variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- prepare
- build
- deploy

# Stage: prepare
##############################################################################

prepare:image-dev:
  stage: prepare
  before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  - apk add make git
  script:
  - make upload-dev
  tags:
  - docker

# Stage: build
##############################################################################

build:image:
  stage: build
  before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  - apk add make git
  script:
  - make upload
  tags:
  - docker

# Stage: deploy
##############################################################################

deploy:kubernetes:
  stage: deploy
  variables:
    KUBECONFIG: /root/.kube/config
  image: registry.git.rwth-aachen.de/acs/internal/cloud/kubernetes/deployment
  before_script:
  - mkdir -p $(dirname ${KUBECONFIG})
  - echo "${KUBECONFIG_ENCODED}" | base64 -d > ${KUBECONFIG}
  - kubectl version
  script:
  - make deploy
  tags:
  - docker
  only:
    refs:
    - master
